config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/responses", to: "response#index"
  get "/search", to: "home#search"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :prompts do
    resources :responses do
      resources :reactions, only: [:index, :create, :destroy]
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @prompt = Prompt.order("RANDOM()").first
  end

  def search
    text = params[:prompt_text]
    # need to change so that it checks regardless of case + mispellings
    if Prompt.exists?(text: text)
      @prompt = Prompt.find_by(text: text)
    else
      @prompt = Prompt.create(text: text)
      @prompt.generate_responses_reactions
    end
    render 'prompts/show'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_login.html.erb
<% if user_signed_in? %>
  <div class="align-center gap-4 flex">
    <p style="white-space: nowrap; overflow: hidden;"><%= current_user.email %></p>
    <p class="bg-white text-black p-2"><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
  </div>
<% else %>
  <%= form_for(:user, url: user_session_path) do |f| %>
    <div class="flex flex-col gap-3 text-{3rem}">
      <div class="flex gap-3 justify-between">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, class: "text-black" %>
      </div>
      <div class="flex gap-3 justify-between">
        <%= f.label :password %>
        <%= f.password_field :password, class: "text-black" %>
      </div>
      <div class="gap-3 flex justify-between">
        <div>
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
        <button class="border border-white rounded py-2 px-4"><%= f.submit "Log in" %></button>
        <button class="border border-white rounded py-2 px-4"><%= link_to "Sign up", new_user_registration_path %></button>
      </div>
    </div>

  <% end %>
<% end %>

app/views/home/_response.html.erb
<div class="border border-black mb-4 px-4 py-2">
  <%= response %>
  <ul class="flex gap-3">
    <li>👍1</li>
    <li>💖3</li>
    <li>😂1</li>
    <li>😲0</li>
    <li>😢6</li>
    <li>😡2</li>
  </ul>
  <p>Submitted by <%= "response.user" %></p>
</div>

app/views/home/_search.html.erb
<%= form_with url: "/search", class: "mb-4 text-black", method: :get do |form| %>
    <div class="flex gap-4 mx-1 text-black">
      <%= form.text_field :prompt_text, class: "border p-2 w-full", placeholder: "Search for a prompt you'd like to see responses for" %>
      <%= form.submit "Search", class: "bg-blue-500 text-white p-2 rounded-lg" %>
    </div>
<% end %>

app/views/home/index.html.erb
<div class="container bg-gray">
  <div class="pt-10 h-screen px-20">
    <div class="flex justify-between mb-5 items-start">
      <h1 class="mx-1 text-2xl font-bold mb-4">What to Say 💭</h1>
      <%= render 'login' %>
    </div>
    <%= render 'search' %>
    <div>
      <h1 class="text-xl font-bold mb-2">Prompt</h1>
      <p class="mb-2"><%= @prompt.text %></p>
      <h3 class="text-lg font-bold mb-4">Responses</h3>
    </div>
      <% @prompt.responses.each do |response| %>
    <div class="border border-white bg-transparent mb-4 px-4 py-2">
      <div>
        <h3><%= response.text %></h3>
      </div>
      <div class="my-3">
        <% if response.user == current_user %>
          <div class="flex">
          <%= link_to "Edit", edit_prompt_response_path(@prompt, response), class: "btn btn-gray mr-2" %>
          <%= link_to "Destroy", prompt_response_path(@prompt, response), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          }, class: "text-black btn btn-gray" %>
        </div>
        <% end %>
      </div>
      <div class="my-3">
        <ul class="flex gap-3">
          <% response.reaction_counts.each do |emotion, count| %>
            <li>
              <% emotion_hash = { "loves" => "💖", "likes" => "👍", "wow" => "😲", "haha" => "😂", "sad" => "😢", "angry" => "😡"} %>
              <% if user_signed_in? %>
                <% if reaction = response.user_reaction(current_user, emotion) %>
                  <%= link_to "#{emotion_hash[emotion] + count.to_s}", prompt_response_reaction_path(prompt_id: @prompt.id, response_id: response.id, id: reaction.id), data: { "turbo-method": :delete } %>
                <% else %>
                  <form action="<%= prompt_response_reactions_path(prompt_id: @prompt.id, response_id: response.id) %>" method="post">
                    <input type="hidden" name="reaction[emotion]" value="<%= emotion %>">
                    <input type="hidden" name="reaction[user_id]" value="<%= current_user.id %>">
                    <input type="hidden" name="reaction[response_id]" value="<%= response.id %>">
                    <input style="opacity: .5" type="submit" value="<%= emotion_hash[emotion] %>"><span><%= count.to_s %></span>
                  </form>
                <% end %>
              <% else %>
                <%= "#{emotion_hash[emotion]} #{count}" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <% if user_signed_in? %>
    <%= render 'responses/form' %>
  <% end %>
  </div>
</div>

app/views/home/prompt.html.erb
<p>Prompt: <%= @prompt.text %></p>